/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UrunlerSlugRouteImport } from './routes/urunler.$slug'
import { Route as AdminSceneRouteImport } from './routes/admin.scene'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunlerSlugRoute = UrunlerSlugRouteImport.update({
  id: '/urunler/$slug',
  path: '/urunler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSceneRoute = AdminSceneRouteImport.update({
  id: '/scene',
  path: '/scene',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/scene': typeof AdminSceneRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/scene': typeof AdminSceneRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/scene': typeof AdminSceneRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/admin/scene' | '/urunler/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/admin/scene' | '/urunler/$slug'
  id: '__root__' | '/' | '/admin' | '/admin/scene' | '/urunler/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  UrunlerSlugRoute: typeof UrunlerSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urunler/$slug': {
      id: '/urunler/$slug'
      path: '/urunler/$slug'
      fullPath: '/urunler/$slug'
      preLoaderRoute: typeof UrunlerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scene': {
      id: '/admin/scene'
      path: '/scene'
      fullPath: '/admin/scene'
      preLoaderRoute: typeof AdminSceneRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSceneRoute: typeof AdminSceneRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSceneRoute: AdminSceneRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  UrunlerSlugRoute: UrunlerSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
