/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UrunlerSlugRouteImport } from './routes/urunler.$slug'
import { Route as AdminSceneRouteImport } from './routes/admin.scene'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminContactRouteImport } from './routes/admin.contact'

const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunlerSlugRoute = UrunlerSlugRouteImport.update({
  id: '/urunler/$slug',
  path: '/urunler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSceneRoute = AdminSceneRouteImport.update({
  id: '/scene',
  path: '/scene',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/iletisim': typeof IletisimRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/scene': typeof AdminSceneRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/iletisim': typeof IletisimRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/scene': typeof AdminSceneRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/iletisim': typeof IletisimRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/scene': typeof AdminSceneRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/iletisim'
    | '/admin/contact'
    | '/admin/projects'
    | '/admin/scene'
    | '/urunler/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/iletisim'
    | '/admin/contact'
    | '/admin/projects'
    | '/admin/scene'
    | '/urunler/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/iletisim'
    | '/admin/contact'
    | '/admin/projects'
    | '/admin/scene'
    | '/urunler/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  IletisimRoute: typeof IletisimRoute
  UrunlerSlugRoute: typeof UrunlerSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urunler/$slug': {
      id: '/urunler/$slug'
      path: '/urunler/$slug'
      fullPath: '/urunler/$slug'
      preLoaderRoute: typeof UrunlerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scene': {
      id: '/admin/scene'
      path: '/scene'
      fullPath: '/admin/scene'
      preLoaderRoute: typeof AdminSceneRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContactRoute: typeof AdminContactRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSceneRoute: typeof AdminSceneRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContactRoute: AdminContactRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSceneRoute: AdminSceneRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  IletisimRoute: IletisimRoute,
  UrunlerSlugRoute: UrunlerSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
